/** Declaration file generated by dts-gen */

export = epub_gen;

declare class epub_gen {
    constructor(...args: any[]);

    downloadAllImage(...args: any[]): void;

    downloadImage(...args: any[]): void;

    genEpub(...args: any[]): void;

    generateTempFile(...args: any[]): void;

    makeCover(...args: any[]): void;

    render(...args: any[]): void;

}

declare namespace epub_gen {
    // @ts-ignore
    namespace prototype {
        function downloadAllImage(...args: any[]): void;

        function downloadImage(...args: any[]): void;

        function genEpub(...args: any[]): void;

        function generateTempFile(...args: any[]): void;

        function makeCover(...args: any[]): void;

        function render(...args: any[]): void;

    }

}

