/** Declaration file generated by dts-gen */


declare class socks_proxy_agent {
    constructor(opts: any);

    callback(req: any, opts: any, fn: any): any;
}

declare namespace socks_proxy_agent {
    function addListener(type: any, listener: any): any;

    function addRequest(req: any, _opts: any): void;

    function callback(req: any, opts: any, fn: any): any;

    function emit(type: any, args: any): any;

    function eventNames(): any;

    function freeSocket(socket: any, opts: any): void;

    function getMaxListeners(): any;

    function listenerCount(type: any): any;

    function listeners(type: any): any;

    function off(type: any, listener: any): any;

    function on(type: any, listener: any): any;

    function once(type: any, listener: any): any;

    function prependListener(type: any, listener: any): any;

    function prependOnceListener(type: any, listener: any): any;

    function rawListeners(type: any): any;

    function removeAllListeners(type: any, ...args: any[]): any;

    function removeListener(type: any, listener: any): any;

    function setMaxListeners(n: any): any;
}
