/** Declaration file generated by dts-gen */

export function cwebp(
    input_image: any,
    output_image: any,
    option: any,
    callback: any
): void;

export function dwebp(
    input_image: any,
    output_image: any,
    option: any,
    callback: any
): void;

export function gwebp(
    input_image: any,
    output_image: any,
    option: any,
    callback: any
): void;

export function webpmux_add(
    input_image: any,
    output_image: any,
    icc_profile: any,
    option: any,
    callback: any
): void;

export function webpmux_animate(
    input_images: any,
    output_image: any,
    loop: any,
    bgcolor: any,
    callback: any
): void;

export function webpmux_extract(
    input_image: any,
    icc_profile: any,
    option: any,
    callback: any
): void;

export function webpmux_getframe(
    input_image: any,
    output_image: any,
    frame_number: any,
    callback: any
): void;

export function webpmux_strip(
    input_image: any,
    output_image: any,
    option: any,
    callback: any
): void;

export namespace cwebp {
    const prototype: {};
}

export namespace dwebp {
    const prototype: {};
}

export namespace gwebp {
    const prototype: {};
}

export namespace webpmux_add {
    const prototype: {};
}

export namespace webpmux_animate {
    const prototype: {};
}

export namespace webpmux_extract {
    const prototype: {};
}

export namespace webpmux_getframe {
    const prototype: {};
}

export namespace webpmux_strip {
    const prototype: {};
}
