module.exports = {
    testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/downloadResult/',
        '/server/types/',
        '/server/dist/',
        '/server/logs/',
        '/server/tmp/',
    ],
    coverageReporters: ['text-summary', 'lcov'],
    collectCoverageFrom: ['**/*.{ts,tsx}'],
    coveragePathIgnorePatterns: [
        '/node_modules/',
        '/server/node_modules/',
        '/dist/',
        '/tmp',
        '/logs',
        '/server/logs',
        '/downloadResult/',
        '/server/types/',
        '/server/dist/',
        '/server/logs/',
        '/server/tmp/',
    ],
    bail: true,
    testURL: 'http://localhost:8080',
};
